### ISSUE TITLE
Hanging on Pixel 6

### ISSUE THREAD

**Issue by breixopd** [capntrips/BootControl#1]
I am on a rooted pixel 6 (normal magisk 27.0) and the app just hangs showing the icon and then stops responding when I try to go on it. The app has been given superuser rights and I get a notification telling me it has been granted the rights on launch but does not go past the splash screen.

**Comment by capntrips** [comment]
I'm seeing the same thing on Pixel 8, so something must have changed with Android 14. I'll look into it.

**Comment by badabing2005** [comment]
FYI Must be something with the March release.
Works on Pixel 5 with A14 which does not have a March release, but doesn't work on Pixel 7 Pro March release nor on One Plus 5 Lineage 21 (A14) March release.

**Comment by capntrips** [comment]
Here's a test build:

~BootControl-v1.0.0-alpha02+08cb6a5.apk.gz~

It is working on `AP1A.240305.019.A1` on Pixel 8. I haven't had a chance to test it on older builds or other devices.

You can find the source [here](https://github.com/capntrips/BootControl/tree/use-jni).

**Comment by badabing2005** [comment]
It crashes on Pixel 7 Pro, and One plus 5
Here's the logcat from P7P

[crash.log](https://github.com/capntrips/BootControl/files/14830151/crash.log)

**Comment by capntrips** [comment]
Whoops. I tested the debug build with minify enabled, but I didn't actually test the release build (for shame, I know). Turns out the issue was related to obfuscation. It's an open source app, so there's no need for that, so I turned it off, and the release builds started working:

[BootControl-v1.0.0-alpha02+5585364.apk.gz](https://github.com/capntrips/BootControl/files/14830465/BootControl-v1.0.0-alpha02%2B5585364.apk.gz)

I tested this release build on both a Pixel 8 on Android 14 and a Nothing Phone 2  on Android 13.

Now I'm off to do some database updates in production.

**Edit:** TIL you can reply to issue threads via email.

**Comment by breixopd** [comment]
Hello,

Thanks for the help! Only just read the emails now.
Thanks so much for your help.

Regards

**Comment by badabing2005** [comment]
Thanks for the update.
It worked on Pixel 7 Pro, but still crashes on One Plus 5 with Lineage.
[1p5_crash.log](https://github.com/capntrips/BootControl/files/14838423/1p5_crash.log)

PS: 1p5 is not a dual slot device.

**Comment by breixopd** [comment]
Seems to work on my Pixel 6 with the March update on it. I'd help you test
on other devices but I don't have anything else to test with.

**Comment by capntrips** [comment]
It makes sense that it wouldn't work on devices with a single slot, since the device won't have the underlying interface to bind to. I suppose I could make it handle that scenario a bit more gracefully.

**Comment by capntrips** [comment]
I added some checks, so this build should handle the the missing module without crashing:

[BootControl-v1.0.0-alpha02+4e3df28.apk.gz](https://github.com/capntrips/BootControl/files/14844329/BootControl-v1.0.0-alpha02%2B4e3df28.apk.gz)

**Comment by badabing2005** [comment]
Thank you, no more crashes.

**Comment by capntrips** [comment]
fixed in `v1.0.0-alpha03`
